spring:
  application:
    name: microservice-admin-center
  security:
    user:
      name: ${eureka.client.security.username}
      password: ${eureka.client.security.password}
  boot:
    admin:
      context-path: /ui
#      discovery:
#        services:

server:
  port: 8080

eureka:
  client:
    registryFetchIntervalSeconds: 5
    security:
      username: admin
      password: 63FUUWO+ghBkrEZL3hCjG3eihTc=
    service-url:
      defaultZone: http://${eureka.client.security.username}:${eureka.client.security.password}@eureka.dev.choicesaas.cn/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: /actuator/health
    metadata-map:
      startup: ${random.int}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

javamelody:
  collectserver.enabled: true
  init-parameters:
    storage-directory: /tmp/javamelody